#!/usr/bin/env perl
#
#

use warnings;
use strict;

use POE qw/Wheel::FollowTail/;

my $device = "/var/log/syslog";
my $gpgkey = "/etc/killallthehumans/humans.key";
my $ramfs = "/mnt/ramfs";
my $shadow = "/mnt/shadow/shadow.gpg";
my $shadow_decrypted = "$ramfs/shadow";
my $file = "/var/log/syslog";

$SIG{INT} = \&_cleanup;
$SIG{TERM} = \&_cleanup;

POE::Session->create(
  inline_states => {
    _start => sub {
      $_[HEAP]->{wheel} = POE::Wheel::FollowTail->new(
        Filename   => $file,
        InputEvent => 'got_line',
        ErrorEvent => 'got_error',
      );
    },
    got_line => sub {
      my ($line, $wheel_id) = @_[ARG0, ARG1];
      my $child = $_[HEAP]{children_by_wid}{$wheel_id};
      if ($line =~ /(sd[a-z][0-9]+)/) {
        my $dev = $1;
        print "${line}\n";

        # XXX: make sure everything is setup for the first time

        # XXX: now we need to clean up and unmount old tmpfs if it exists
        system("shred -u -n 1 $shadow_decrypted &> /dev/null");
        system("umount $ramfs");

        # XXX: make new tmpfs and mount
        system("mount -t ramfs -o size=1m ramfs $ramfs");

        # XXX: once device is mounted do a decrypt and write data out to ramfs
        system("gpg -d -q --batch -o $shadow_decrypted --passphrase-fd 3 3<$gpgkey <$shadow");
      }
    },
    got_error => sub {
      my ($line, $wheel_id) = @_[ARG0, ARG1];
      my $child = $_[HEAP]{children_by_wid}{$wheel_id};
      warn "${line}\n"
    },
  },
  args => [$file],
);

POE::Kernel->run();

sub _cleanup {
  # XXX: do some cleanup on tempfs
  print "KILL ALL THE ... wait, me?\n";
  exit 0;
}

exit 0;
