#!/usr/bin/env perl
#
#

use warnings;
use strict;

use POE qw/Wheel::FollowTail/;

my $file = "/var/log/syslog";

$SIG{INT} = \&_cleanup;
$SIG{TERM} = \&_cleanup;

POE::Session->create(
  inline_states => {
    _start => sub {
      $_[HEAP]->{wheel} = POE::Wheel::FollowTail->new(
        Filename   => $file,
        InputEvent => 'got_line',
        ErrorEvent => 'got_error',
      );
    },
    got_line => sub {
      my ($line, $wheel_id) = @_[ARG0, ARG1];
      my $child = $_[HEAP]{children_by_wid}{$wheel_id};
      if ($line =~ /(sd[a-z][0-9]+)/) {
        my $dev = $1;
        print "${line}\n";

        # XXX: make sure everything is setup for the first time

        # XXX: now we need to clean up and unmount old tmpfs if it exists

        # XXX: make new tmpfs 

        # XXX: now mount device

        # XXX: once device is mounted validate file encryption

        # XXX: write data out to tmpfs

        # XXX: remake the symlink
      }
    },
    got_error => sub {
      my ($line, $wheel_id) = @_[ARG0, ARG1];
      my $child = $_[HEAP]{children_by_wid}{$wheel_id};
      warn "${line}\n"
    },
  },
  args => [$file],
);

POE::Kernel->run();

sub _cleanup {
  # XXX: do some cleanup on tempfs
  print "KILL ALL THE ... wait, me?\n";
  exit 0;
}

exit 0;
