#! /bin/sh
### BEGIN INIT INFO
# Provides:          killallthehumans
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      6
# Short-Description: All the humans, kill them.
# Description:
### END INIT INFO

. /lib/lsb/init-functions

do_stop () {
    echo "no u"
}

case "$1" in
  start)
	# No-op
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	do_stop
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
